In [1]:
import pandas as pd
import requests
import numpy as np
import time
import folium
import matplotlib.pyplot as plt
import json

In [2]:
# Load existing data if available
try:
    distance_df = pd.read_csv("data/osrm_distance_matrix_new.csv", index_col=0)
    distance_matrix = distance_df.values
    print(distance_df.shape)
    duration_df = pd.read_csv("data/osrm_duration_matrix_new.csv", index_col=0)
    duration_matrix = duration_df.values
    existing_codes = duration_df.index.tolist()  # Get existing codes from the index
except FileNotFoundError:
    print("No previous data found. Starting fresh.")
    distance_matrix = np.zeros((0, 0))  # Initialize empty matrices
    duration_matrix = np.zeros((0, 0))
    existing_codes = []

(758, 758)

In [3]:
# Load new data from CSV
day = "14-07-2025"
new_data = pd.read_csv(f"../data/test/orders-vol/{day}-PO-3.csv")
new_data = new_data.dropna(subset=['CODE'])


if np.issubdtype(new_data['CODE'].dtype, np.number):
    new_data['CODE'] = new_data['CODE'].astype(int)
    new_data['CODE'] = new_data['CODE'].astype(str)
    print('Converting to Object')

In [4]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CODE       37 non-null     object
 1   SALE       37 non-null     float64
 2   VOLUME     37 non-null     float64
 3   DATE       37 non-null     object
 4   LOCATION   37 non-null     object
 5   ADDRESS    37 non-null     object
 6   LATITUDE   37 non-null     float64
 7   LONGITUDE  37 non-null     float64
 8   BRAND      37 non-null     object
 9   DISTRICT   37 non-null     object
dtypes: float64(4), object(6)
memory usage: 3.0+ KB

In [5]:
(new_data['CODE']).dtype

dtype('O')

In [6]:
# # #Load new data from CSV
master_data = pd.read_csv('data/master_gps.csv')
master_data = master_data.dropna(subset=['CODE'])

In [7]:
SMAK_KADAWATHA = (7.0038321,79.9394804)

smak_data = {
    "CODE":'0',
    "LOCATION":"SMAK",
    "ADDRESS":"Smak, Kadawatha, Western Province, Sri Lanka",
    "LATITUDE":SMAK_KADAWATHA[0],
    "LONGITUDE":SMAK_KADAWATHA[1],
    "BRAND":"SMAK"
}


master_data = pd.concat(
    [
        pd.DataFrame(smak_data, index=[0]),
        master_data
    ],
    ignore_index=True
)

master_data = master_data.drop_duplicates(subset=['CODE'], keep='first')

In [8]:
print(new_data.columns)
print(master_data.columns)

Index(['CODE', 'SALE', 'VOLUME', 'DATE', 'LOCATION', 'ADDRESS', 'LATITUDE',
       'LONGITUDE', 'BRAND', 'DISTRICT'],
      dtype='object')
Index(['CODE', 'LOCATION', 'ADDRESS', 'LATITUDE', 'LONGITUDE', 'BRAND',
       'DISTRICT'],
      dtype='object')

In [9]:
master_data

,CODE,LOCATION,ADDRESS,LATITUDE,LONGITUDE,BRAND,DISTRICT
0,0,SMAK,"Smak, Kadawatha, Western Province, Sri Lanka",7.003832,79.939480,SMAK,NaN
2,3,Wattala SC,"Wattala, Sri Lanka",6.990668,79.893171,Arpico,Gampaha
3,4,Borelasgamuwa SS,"Borelasgamuwa, Sri Lanka",6.840989,79.901719,Arpico,Colombo
4,5,Hyde Park SC,"Hyde, Sri Lanka",6.917587,79.858519,Arpico,Colombo
5,10,Nawinna SC,"Nawinna, Sri Lanka",6.853331,79.915072,Arpico,Colombo
...,...,...,...,...,...,...,...
717,1855,EX MIRISWATTA,MIRISWATTA,7.072739,80.015763,Cargills,Gampaha
718,1856,EX KIMBULAPITIYA,KIMBULAPITIYA,7.204241,79.894081,Cargills,Gampaha
719,1857,EX WILIMBULA,WILIMBULA,7.873054,80.771797,Cargills,Unknown
720,1861,EX KATANA,KATANA,7.248028,79.899366,Cargills,Gampaha
721,1905,FC NEGOMBO 03,NEGOMBO 03,7.205521,79.851256,Cargills,Gampaha

In [10]:
new_data = new_data[['CODE', 'LOCATION', 'ADDRESS', 'LATITUDE', 'LONGITUDE', 'BRAND','DISTRICT']]

In [11]:
updated_master = pd.concat(
    [master_data,
    new_data],
    ignore_index = True
).drop_duplicates(subset=['CODE'], keep='first')

In [ ]:
# updated_master.to_csv('data/master_gps.csv', index=False)

In [13]:
updated_master

,CODE,LOCATION,ADDRESS,LATITUDE,LONGITUDE,BRAND,DISTRICT
0,0,SMAK,"Smak, Kadawatha, Western Province, Sri Lanka",7.003832,79.939480,SMAK,NaN
1,3,Wattala SC,"Wattala, Sri Lanka",6.990668,79.893171,Arpico,Gampaha
2,4,Borelasgamuwa SS,"Borelasgamuwa, Sri Lanka",6.840989,79.901719,Arpico,Colombo
3,5,Hyde Park SC,"Hyde, Sri Lanka",6.917587,79.858519,Arpico,Colombo
4,10,Nawinna SC,"Nawinna, Sri Lanka",6.853331,79.915072,Arpico,Colombo
...,...,...,...,...,...,...,...
753,Rathmalana,Rathmalana,Rathmalana,6.819545,79.880083,Laugf,Colombo
754,Seeduwa,Seeduwa,Seeduwa,7.124708,79.875003,Laugf,Gampaha
755,Wattala,Wattala,Wattala,6.990668,79.893171,Laugf,Gampaha
756,Wellawatta,Wellawatta,Wellawatta,6.875531,79.860998,Laugf,Colombo
757,Werahera,Werahera,Werahera,6.828005,79.905277,Laugf,Colombo

In [14]:
# Extract locations and codes from new data
updated_master_codes = updated_master[['CODE', 'LATITUDE', 'LONGITUDE']].drop_duplicates(subset=['CODE'], keep='first')
updated_master_codes_list = updated_master_codes['CODE'].tolist()
updated_master_gps_list = [(row['LATITUDE'], row['LONGITUDE']) for _, row in updated_master_codes.iterrows()]

In [15]:
# Identify codes that are not in the existing matrix
codes_to_add = [code for code in updated_master_codes_list if code not in existing_codes]
locations_to_add = [loc for i, loc in enumerate(updated_master_gps_list) if updated_master_codes_list[i] in codes_to_add]

In [16]:
len(codes_to_add), len(locations_to_add)

(0, 0)

In [17]:
existing_locations = list(zip(updated_master['LATITUDE'], updated_master['LONGITUDE']))

In [18]:
len(existing_locations)

758

In [19]:
existing_locations

[(7.0038321, 79.9394804),
 (6.9906677, 79.8931709),
 (6.8409891, 79.9017187),
 (6.9175873, 79.8585189),
 (6.8533309, 79.9150724),
 (5.9496309, 80.5468529),
 (6.7106361, 79.9074262),
 (6.8411652, 79.9654324),
 (6.0328948, 80.2167912),
 (6.9060787, 79.9696277),
 (7.4817695, 80.3608876),
 (6.8624842, 79.8854983),
 (6.8432762, 80.0031833),
 (7.0864153, 80.0335107),
 (7.2513317, 80.3463754),
 (6.8758648, 79.9391936),
 (6.9906677, 79.8931709),
 (7.2657063, 79.8591235),
 (7.3096237, 80.7103532),
 (7.3359903, 80.6214005),
 (7.1842076, 79.9500477),
 (6.549971, 79.9836108),
 (7.1247085, 79.8750028),
 (6.9778284, 79.9271523),
 (7.0280037, 79.923),
 (6.8723185, 80.0003875),
 (7.0318781, 80.0283415),
 (7.472123, 80.0446221),
 (6.2441521, 80.0590804),
 (7.3493037, 79.8352767),
 (6.8261828, 79.881483),
 (7.0477897, 79.8970348),
 (6.92695, 79.9307072),
 (7.5619894, 79.8016569),
 (7.3529789, 80.6132646),
 (6.8472579, 80.0674619),
 (6.7055742, 80.3847345),
 (8.3113518, 80.4036508),
 (6.6235199, 80.5430499),
 (6.8979941, 79.9222869),
 (6.8559485, 79.8629683),
 (7.0840484, 80.0098314),
 (6.8740921, 79.8604934),
 (7.2055208, 79.8512562),
 (7.2905715, 80.6337262),
 (6.8017575, 79.9227313),
 (6.5853948, 79.96074),
 (7.3018682, 80.593833),
 (6.8682271, 79.8930046),
 (6.9205009, 79.8658211),
 (7.2744094, 80.6111499),
 (7.4817695, 80.3608876),
 (6.8411652, 79.9654324),
 (7.2055208, 79.8512562),
 (6.8964191, 79.8884819),
 (6.8301185, 79.8800832),
 (6.9060787, 79.9696277),
 (6.9009, 79.8707),
 (6.8758648, 79.9391936),
 (7.0477897, 79.8970348),
 (7.2858881, 80.6264778),
 (6.9906677, 79.8931709),
 (6.8723185, 80.0003875),
 (6.8860799, 79.9626354),
 (6.8525143, 79.8976618),
 (6.9171044, 79.8481871),
 (6.8733711, 79.9171546),
 (6.8501667, 79.8725682),
 (6.8675496, 79.9100845),
 (6.8693128, 79.8894317),
 (6.838935, 79.9784204),
 (6.8872296, 79.8647003),
 (6.9481824, 79.8615896),
 (6.8798307, 79.9029517),
 (6.8660607, 79.8753067),
 (6.8845527, 79.9019512),
 (6.7998133, 79.8842826),
 (6.8423416, 79.91794),
 (6.8896173, 79.8553873),
 (6.8496658, 79.9235834),
 (6.8647757, 79.8632349),
 (6.9059941, 79.894945),
 (6.8802431, 79.9475213),
 (6.8435174, 79.9581664),
 (6.9087426, 79.9436659),
 (6.8638002, 79.8875011),
 (6.9103636, 79.8936349),
 (6.816062, 79.8769278),
 (6.8414636, 79.9014475),
 (6.9094108, 79.8942538),
 (6.8936437, 79.8704269),
 (6.9082532, 79.9447799),
 (6.9197379, 79.8589027),
 (6.8549219, 79.9064625),
 (6.0328817, 80.2152229),
 (6.9773951, 79.9296825),
 (6.9512173, 79.9078132),
 (7.0243153, 79.899739),
 (6.9887181, 79.8913253),
 (6.4190267, 80.0024827),
 (7.279561, 80.6198891),
 (7.2905715, 80.6337262),
 (5.9478241, 80.5344474),
 (6.8441906, 79.9686816),
 (6.8749467, 79.9364678),
 (6.9906677, 79.8931709),
 (6.6993724, 80.379375),
 (6.9977837, 79.9189814),
 (6.9786855, 79.9277),
 (6.0599745, 80.2021933),
 (6.5654599, 79.9676493),
 (6.8792387, 79.8764553),
 (6.9736276, 79.9208395),
 (6.7684114, 79.8868727),
 (7.4832133, 80.3587461),
 (6.7919378, 79.9300883),
 (6.4730375, 79.984256),
 (7.0270252, 79.9150162),
 (6.9278516, 79.9106324),
 (5.9471016, 80.5625956),
 (6.846864, 79.8851625),
 (6.7096021, 79.9210634),
 (7.452174, 80.6133841),
 (7.0849349, 80.0087892),
 (6.8444164, 80.0065919),
 (7.091585, 79.8884605),
 (6.4190267, 80.0024827),
 (6.4425457, 79.9922648),
 (6.9319982, 79.907722),
 (6.8017575, 79.9227313),
 (7.2532238, 80.3454101),
 (7.1694282, 79.9520782),
 (6.3162324, 80.8433145),
 (7.083344, 79.8926809),
 (7.3439464, 79.840831),
 (6.9289776, 79.9277399),
 (7.4880602, 80.3632963),
 (6.7604617, 79.8975639),
 (7.204378, 79.876023),
 (7.1593375, 80.5627166),
 (7.5686716, 79.7995779),
 (6.7919378, 79.9300883),
 (6.8562078, 79.8785357),
 (7.2154132, 79.84165),
 (7.0147657, 79.9690126),
 (6.9084066, 79.9446174),
 (6.8550009, 80.2599776),
 (7.4146725, 79.828922),
 (7.4975346, 80.6243663),
 (7.3183255, 80.6293876),
 (6.7188231, 79.9930907),
 (7.7612443, 80.1120736),
 (7.0754409, 80.0143367),
 (6.8952571, 79.9505987),
 (6.928269, 79.8636961),
 (7.1208728, 80.0636742),
 (6.9270786, 79.861243),
 (6.0265276, 80.7948493),
 (6.8054739, 79.9263413),
 (6.9716722, 79.8786833),
 (7.1928611, 79.8604831),
 (7.0673864, 79.8934866),
 (7.1231431, 79.8783888),
 (6.8802431, 79.9475213),
 (6.9084066, 79.9446174),
 (7.2816136, 80.6209311),
 (7.0739735, 79.85717),
 (6.9409466, 80.1963047),
 (6.9482114, 79.9386028),
 (6.0651597, 80.2233789),
 (6.242438, 80.0492057),
 (6.8796442, 79.9458337),
 (6.8802431, 79.9475213),
 (6.9871489, 79.977399),
 (6.8756534, 79.9358023),
 (6.4190267, 80.0024827),
 (7.0371109, 79.9917576),
 (5.946619, 80.5391642),
 (6.7962213, 79.8964871),
 (6.8426283, 79.9262647),
 (6.6099352, 79.9527322),
 (6.8943914, 79.8570867),
 (8.3259528, 80.4053739),
 (6.9313808, 79.9766195),
 (6.8845527, 79.9019512),
 (6.6810724, 80.3981326),
 (7.0824867, 80.030854),
 (6.9532197, 79.867138),
 (6.8781436, 79.8906725),
 (6.9019412, 79.8590374),
 (7.146577, 79.9336968),
 (7.0603059, 79.9627325),
 (6.9108052, 79.8891173),
 (6.9202229, 79.855804),
 (7.2926093, 80.6370454),
 (6.8940731, 79.8546195),
 (6.8311676, 80.9887048),
 (7.2310915, 80.2450189),
 (6.9356673, 79.8447204),
 (7.4884909, 80.3606378),
 (5.9494158, 80.5447271),
 (7.091585, 79.8884605),
 (6.8512992, 79.865918),
 (6.7055742, 80.3847345),
 (6.9097726, 79.8501472),
 (6.8936437, 79.8704269),
 (5.9496309, 80.5468529),
 (6.9347204, 79.8685915),
 (7.2532238, 80.3454101),
 (6.4345732, 80.0003875),
 (6.9486466, 79.859476),
 (6.2441521, 80.0590804),
 (6.8894063, 79.8768789),
 (6.4730375, 79.984256),
 (7.3212616, 80.6275089),
 (7.2285555, 80.200415),
 (6.9166038, 79.8649075),
 (7.467465, 80.6234161),
 (6.8824961, 79.8696014),
 (6.9503517, 80.2137488),
 (6.0333366, 80.2154182),
 (6.8948227, 79.8547493),
 (6.3162324, 80.8433145),
 (8.3316899, 80.4091268),
 (6.9716722, 79.8786833),
 (6.8948227, 79.8547493),
 (6.6478307, 80.7002674),
 (6.9240228, 79.8686059),
 (6.9880291, 81.0599529),
 (8.7497702, 80.4965416),
 (7.265568, 80.5558208),
 (7.874217, 80.6511287),
 (5.9716762, 80.6951041),
 (7.3693372, 80.6173431),
 (6.1283566, 81.1258669),
 (6.8927975, 80.5972816),
 (7.2802929, 80.6740597),
 (6.0257603, 80.758582),
 (6.0705817, 80.2251603),
 (6.8485638, 80.26001),
 (7.0558093, 80.5345494),
 (8.5768576, 81.2098826),
 (7.2521971, 80.4493629),
 (8.5873638, 81.2152121),
 (7.472876, 80.0443989),
 (6.6993724, 80.379375),
 (7.3323183, 80.0278438),
 (7.7141071, 81.6961912),
 (6.4447452, 80.0168602),
 (7.2622176, 80.5929912),
 (7.3017563, 81.6747295),
 (6.8867474, 79.8588715),
 (6.9443444, 79.8670732),
 (6.8716513, 81.3512451),
 (8.0719177, 80.546471),
 (6.8791262, 80.2429977),
 (6.8949964, 79.8667069),
 (6.9024028, 79.8545389),
 (9.7232349, 79.9973669),
 (6.9065768, 79.8871277),
 (9.6711487, 80.0115901),
 (7.2268544, 81.8505496),
 (7.4143831, 81.8306334),
 (6.9223969, 79.8659984),
 (6.9038765, 79.8781829),
 (7.6239144, 80.2433145),
 (6.7739916, 80.3676071),
 (7.0458735, 80.2537063),
 (7.2963549, 80.7301035),
 (7.9353523, 81.0180545),
 (9.4061536, 80.4082787),
 (6.7972669, 79.9099368),
 (7.1243401, 80.2871828),
 (6.903517, 80.91281),
 (7.7298995, 81.6742784),
 (6.4255312, 79.997709),
 (7.7565045, 80.5771737),
 (7.3595985, 80.3066891),
 (6.8752706, 81.8306334),
 (6.9160121, 79.8701693),
 (7.7768972, 81.6042028),
 (7.6449706, 80.5077237),
 (9.7980091, 80.1779516),
 (7.3633212, 81.7977421),
 (6.036083, 80.744546),
 (6.2791538, 81.2876691),
 (6.2456851, 80.7655493),
 (7.9864944, 80.2878794),
 (6.9478313, 80.0152972),
 (9.7434617, 80.0274205),
 (7.4709328, 80.623242),
 (7.2467402, 80.1290871),
 (6.4683752, 80.0795258),
 (6.4683752, 80.0795258),
 (7.295006, 80.7344557),
 (6.1225999, 81.0237594),
 (6.035213, 80.2171656),
 (6.2703717, 80.0913687),
 (7.3212616, 80.6275089),
 (6.9462153, 79.9892034),
 (6.2441521, 80.0590804),
 (6.922196, 79.8645896),
 (6.7589233, 81.2491298),
 (6.0968214, 80.4770544),
 (7.2707766, 80.6048083),
 (7.0558093, 80.5345494),
 (7.2690783, 80.6648328),
 (5.9773782, 80.4288487),
 (6.115667, 80.1200582),
 (6.9349198, 80.3380213),
 (5.9936463, 80.2688039),
 (8.0322147, 80.7519272),
 (7.3693372, 80.6173431),
 (9.6652238, 80.0137285),
 (6.9113889, 79.8866667),
 (7.5451185, 80.445106),
 (6.731289, 81.1019688),
 (6.5041545, 80.6528607),
 (8.5410253, 80.4880392),
 (7.2816136, 80.6209311),
 (7.3300102, 80.4111999),
 (6.3159694, 80.5171662),
 (6.5241762, 80.0862699),
 (6.0330145, 80.2390163),
 (6.8509933, 79.8625996),
 (7.467465, 80.6234161),
 (7.3727606, 80.5244948),
 (7.873054, 80.771797),
 (7.3813156, 80.5867633),
 (7.8768056, 80.0117638),
 (6.5094589, 79.9819466),
 (6.9379638, 79.878569),
 (6.0328948, 80.2167912),
 (7.427258, 80.2140717),
 (5.97329, 80.4103),
 (7.4778098, 80.3383375),
 (6.8138371, 79.9359634),
 (6.4135463, 81.3325679),
 (8.9809743, 79.9044149),
 (7.4137924, 81.8272433),
 (8.042103, 80.593833),
 (6.9235507, 79.9136433),
 (6.9347092, 79.8674354),
 (7.3316371, 80.5699329),
 (5.9430934, 80.5543934),
 (8.3113518, 80.4036508),
 (7.4817695, 80.3608876),
 (7.8681306, 80.6455959),
 (7.2511422, 80.341834),
 (7.3410759, 80.9935897),
 (6.6824903, 80.4052517),
 (6.8431887, 81.002301),
 (5.948262, 80.4715866),
 (6.9590765, 80.2235468),
 (6.4402017, 79.9942713),
 (7.2640563, 80.5389834),
 (6.930624, 79.8624312),
 (6.349044, 80.0978637),
 (6.8413315, 80.005132),
 (7.3135237, 80.3881333),
 (6.2887341, 80.1631349),
 (6.9173305, 79.8554352),
 (6.0655969, 80.268081),
 (6.6898851, 80.3909164),
 (6.88653, 79.8549241),
 (7.5300546, 80.6260748),
 (6.9390215, 79.9871152),
 (6.9381743, 79.8604831),
 (6.9038765, 79.8781829),
 (7.2583458, 80.599485),
 (6.0198256, 80.2477127),
 (6.9097726, 79.8501472),
 (6.8501667, 79.8725682),
 (7.9426827, 81.0116445),
 (6.9386902, 79.8747583),
 (6.0836306, 80.2962385),
 (7.1451675, 80.7852471),
 (6.9352993, 79.8807831),
 (6.9344434, 79.9961936),
 (6.9529494, 79.8702837),
 (7.1635434, 80.5702443),
 (6.9283596, 79.8949946),
 (7.472123, 80.0446221),
 (6.8765025, 79.8652516),
 (6.0705817, 80.2251603),
 (5.9463714, 80.5132818),
 (7.467465, 80.6234161),
 (6.9117245, 79.8614617),
 (7.2679259, 80.5749643),
 (6.0459387, 80.2252201),
 (6.9543289, 80.2045768),
 (6.9934009, 81.0549815),
 (6.5219432, 80.1136852),
 (7.4321631, 80.4437781),
 (6.9257119, 79.8503314),
 (6.9018407, 79.8692882),
 (6.9194938, 79.9780178),
 (7.4817695, 80.3608876),
 (7.162409, 81.22159),
 (6.0243383, 80.7940726),
 (6.4184828, 80.823938),
 (6.2652802, 80.491047),
 (6.3132776, 80.0409178),
 (8.3512634, 81.0069928),
 (7.9483156, 81.0017827),
 (6.5417313, 80.0433503),
 (6.0304592, 80.2150207),
 (6.1688292, 80.1793976),
 (6.9934009, 81.0549815),
 (6.7602835, 80.8809283),
 (7.5554101, 80.456443),
 (8.0348657, 79.7315747),
 (6.4631156, 80.4307831),
 (6.3419553, 80.2377078),
 (7.9181144, 80.2404959),
 (6.0765847, 80.1958755),
 (6.4872288, 80.6937177),
 (7.1045281, 80.336047),
 (6.0243383, 80.7940726),
 (6.0133387, 80.5660041),
 (6.1508888, 80.6937177),
 (6.1382193, 80.1344842),
 (7.2954302, 80.2366261),
 (7.6155983, 80.6354665),
 (6.9407856, 79.852666),
 (7.0288824, 80.2955419),
 (6.9138726, 79.8525287),
 (7.6579606, 80.3686488),
 (8.7542029, 80.4982402),
 (6.7266167, 80.0164621),
 (6.8472579, 80.0674619),
 (6.3065297, 80.6306103),
 (5.9637528, 80.6132646),
 (7.3153819, 80.7449309),
 (7.5008975, 80.3477676),
 (7.4689738, 80.302307),
 (6.1394676, 80.1062861),
 (7.3314137, 81.8333656),
 (6.0935429, 80.8626864),
 (6.1476081, 80.7633743),
 (7.0947226, 80.2822811),
 (8.1540015, 80.3045967),
 (6.9110572, 79.8711168),
 (6.0641685, 80.2617413),
 (7.6569501, 81.7404134),
 (8.4579065, 81.2684019),
 (9.7045948, 80.0523031),
 (6.2774947, 81.2670255),
 (6.9180122, 79.885249),
 (7.517478, 81.7871336),
 (7.4216724, 80.3296664),
 (6.8881939, 79.8677688),
 (7.9213276, 81.5246705),
 (6.8281188, 79.9738229),
 (6.9406131, 79.8789441),
 (6.8301185, 79.8800832),
 (6.8510951, 79.9212011),
 (6.8808992, 79.9052768),
 (6.8649081, 79.8996789),
 (6.9060787, 79.9696277),
 (6.9094108, 79.8942538),
 (7.0840484, 80.0098314),
 (6.8017575, 79.9227313),
 (6.8964191, 79.8884819),
 (6.8624842, 79.8854983),
 (6.8740921, 79.8604934),
 (6.9517846, 79.9132991),
 (6.8411652, 79.9654324),
 (6.9283596, 79.8949946),
 (6.8432762, 80.0031833),
 (6.847802, 79.8723837),
 (6.929061, 79.9827754),
 (6.8643687, 79.8970403),
 (6.908863, 79.9313567),
 (6.8551817, 79.9087754),
 (6.8624842, 79.8854983),
 (6.8689647, 79.9038774),
 (6.8649081, 79.8996789),
 (6.8510951, 79.9212011),
 (6.8723185, 80.0003875),
 (6.9094108, 79.8942538),
 (6.8463993, 79.9484346),
 (6.8164327, 79.9206694),
 (6.8979941, 79.9222869),
 (6.9060787, 79.9696277),
 (6.8659667, 80.0129679),
 (6.8552665, 79.881483),
 (6.8135488, 79.9724245),
 (7.3274866, 80.2934522),
 (6.8604633, 79.9446302),
 (6.9896112, 79.9738229),
 (6.9248928, 79.9380375),
 (6.9750337, 80.1180967),
 (6.8017575, 79.9227313),
 (6.9066865, 80.0522928),
 (6.8172516, 79.9598383),
 (6.8559758, 79.9780178),
 (6.7288686, 80.0297389),
 (6.8699679, 79.9920576),
 (6.7563403, 80.0171609),
 (6.8827383, 79.8683695),
 (6.9345136, 79.9059766),
 (6.8914832, 79.9052768),
 (6.9141883, 79.9150724),
 (6.8411652, 79.9654324),
 (6.8758648, 79.9391936),
 (6.9752231, 79.9206694),
 (6.8755381, 79.8947554),
 (6.9123126, 79.9514464),
 (6.40053, 80.2120618),
 (6.8665559, 79.9150724),
 (6.8280052, 79.9052768),
 (6.8432762, 80.0031833),
 (6.8418059, 79.8665045),
 (6.8604633, 79.9446302),
 (6.9264231, 79.9339124),
 (6.929061, 79.9827754),
 (6.9288713, 79.9027493),
 (6.8017575, 79.9227313),
 (6.8693785, 79.9234678),
 (6.908863, 79.9313567),
 (6.9424282, 79.9045771),
 (6.8551817, 79.9087754),
 (6.7953487, 79.9234678),
 (7.121557, 79.9101748),
 (6.8382446, 79.9414907),
 (6.8743192, 79.9696277),
 (6.9517846, 79.9132991),
 (6.8694191, 79.8979063),
 (6.8516746, 80.0327001),
 (6.860707, 79.8688827),
 (6.8432762, 80.0031833),
 (6.8723185, 80.0003875),
 (6.9060787, 79.9696277),
 (6.7899358, 79.9808143),
 (6.9778284, 79.9271523),
 (6.9908661, 79.9395566),
 (6.9189465, 79.8898816),
 (6.9778284, 79.9271523),
 (6.8743192, 79.9696277),
 (6.8808992, 79.9052768),
 (6.8646859, 79.8949669),
 (6.8261828, 79.881483),
 (6.8411652, 79.9654324),
 (6.7206865, 79.9868167),
 (6.846609, 79.9512139),
 (6.8909701, 79.9227651),
 (7.0144382, 79.8954802),
 (6.8631414, 79.8786833),
 (6.6307411, 80.0045811),
 (7.0300386, 79.9877414),
 (6.2706622, 80.144254),
 (7.121557, 79.9101748),
 (6.8213291, 80.0415729),
 (7.9080663, 79.82127),
 (6.8468057, 79.9822126),
 (6.0521364, 80.2167942),
 (6.8395208, 79.9500477),
 (6.8341477, 80.0039686),
 (6.9345136, 79.9059766),
 (6.9094108, 79.8942538),
 (6.8404081, 79.9008379),
 (6.7196794, 79.9077578),
 (6.7229806, 80.0646682),
 (7.1663889, 79.9467343),
 (6.5853948, 79.96074),
 (6.549971, 79.9836108),
 (6.8195453, 79.8800832),
 (6.7196794, 79.9077578),
 (7.0280037, 79.923),
 (6.8562846, 79.8890356),
 (6.5853948, 79.96074),
 (6.7786701, 79.9472502),
 (6.7196794, 79.9077578),
 (7.0403062, 80.1317396),
 (6.7862384, 79.8926197),
 (6.7866384, 79.8928197),
 (6.2783546, 80.0403047),
 (7.2237702, 80.0182953),
 (6.6949013, 79.9178709),
 (6.8420691, 79.9084475),
 (6.7113091, 79.9458514),
 (6.5853948, 79.96074),
 (7.5686, 80.62758),
 (7.2289814, 79.9906015),
 (6.6362823, 79.9528451),
 (6.7880706, 79.8912813),
 (6.8195453, 79.8800832),
 (6.9078637, 80.0775493),
 (7.1022913, 79.9094751),
 (6.7229806, 80.0646682),
 (6.7493623, 79.9031776),
 (7.1433258, 79.8737728),
 (6.7869384, 79.8948197),
 (6.6362823, 79.9528451),
 (6.8139074, 79.8947804),
 (6.7414417, 79.9031776),
 (6.7126923, 79.9865155),
 (7.1663889, 79.9467343),
 (6.549971, 79.9836108),
 (6.8562846, 79.8890356),
 (7.0411825, 80.1289324),
 (6.8937244, 79.9486489),
 (7.0208119, 79.9325396),
 (7.2299603, 79.8548823),
 (6.9610588, 79.9087754),
 (6.8195453, 79.8800832),
 (6.9863638, 79.9074482),
 (6.9517846, 79.9132991),
 (7.0187475, 79.9108744),
 (7.123191, 79.9241673),
 (6.8434889, 80.0908396),
 (7.1586135, 80.028624),
 (6.7403769, 80.1624543),
 (6.9397165, 80.1369268),
 (6.784184, 80.0541909),
 (6.9523994, 80.0939978),
 (7.1324802, 79.9542438),
 (6.8557161, 80.0926014),
 (7.1210003, 79.9150724),
 (6.3354424, 80.0339312),
 (6.6941127, 80.0730491),
 (6.5186103, 79.9947956),
 (6.8195453, 79.8800832),
 (6.679771, 80.1628703),
 (7.2220533, 79.9780178),
 (7.0280037, 79.923),
 (6.7918869, 79.8842826),
 (6.8391599, 79.8835028),
 (6.8298077, 80.9941178),
 (6.8827383, 79.8683695),
 (6.919566, 79.9269549),
 (7.2989123, 80.6506767),
 (6.1655689, 80.9031172),
 (7.2391815, 80.5924449),
 (7.3273716, 80.5950278),
 (7.5619894, 79.8016569),
 (7.1553708, 80.0576014),
 (6.8301185, 79.8800832),
 (6.9035383, 79.8681098),
 (6.8014572, 79.8996789),
 (6.0827767, 80.6469843),
 (7.8152387, 80.4043131),
 (8.0407913, 79.839386),
 (7.2427345, 80.1269539),
 (8.0426714, 80.955026),
 (6.894662, 80.0562864),
 (6.6898822, 80.8045568),
 (9.70218, 80.0354029),
 (6.9095794, 79.9005022),
 (6.9326744, 79.8413641),
 (7.205520799999999, 79.8512562),
 (7.0667984, 79.90409319999999),
 (7.577715500000001, 79.7943865),
 (7.004632399999999, 79.954155),
 (7.341191200000001, 79.84200129999999),
 (6.9574476, 79.88954869999999),
 (7.0477897, 79.8970348),
 (7.1247085, 79.87500279999999),
 (7.142363899999999, 80.1037721),
 (7.1801543, 79.8842495),
 (7.004632399999999, 79.954155),
 (7.247461100000001, 80.1295079),
 (6.987854, 80.0157633),
 (7.033592199999999, 80.027151),
 (7.205520799999999, 79.8512562),
 (7.1828704, 79.86896229999999),
 (7.166710300000001, 80.1233175),
 (7.0477897, 79.8970348),
 (7.1246978, 79.8750441),
 (7.0629241, 79.8688837),
 (7.3706207, 79.8352767),
 (7.241776299999999, 80.2112164),
 (7.154055199999999, 80.05937519999999),
 (7.1017406, 79.88428259999999),
 (7.873053999999999, 80.77179699999999),
 (7.411783000000001, 79.8653693),
 (7.125554699999999, 80.1108524),
 (7.0277559, 79.8982793),
 (7.0859333, 80.03341809999999),
 (6.9723932, 79.9475487),
 (7.0667984, 79.90409319999999),
 (7.119584700000001, 80.0639697),
 (7.1005259, 80.01157010000001),
 (7.2974635, 79.8821881),
 (6.996137699999999, 79.8765835),
 (7.413063, 79.8309074),
 (7.1380617, 79.9951044),
 (7.062395899999999, 79.9668308),
 (7.577715500000001, 79.7943865),
 (7.0074315, 80.026241),
 (6.9778284, 79.9271523),
 (6.997783699999999, 79.91898139999999),
 (7.1406334, 79.9013603),
 (7.1928611, 79.8604831),
 (7.004632399999999, 79.954155),
 (7.142363899999999, 80.1037721),
 (7.0915358, 79.99477619999999),
 (7.0393941, 79.9564844),
 (7.0277559, 79.8982793),
 (6.9852818, 79.8954802),
 (7.341191200000001, 79.84200129999999),
 (7.062395899999999, 79.9668308),
 (6.990667699999999, 79.8931709),
 (7.265706300000001, 79.8591235),
 (7.0859333, 80.03341809999999),
 (7.205520799999999, 79.8512562),
 (7.2280455, 79.840822),
 (7.188568699999999, 79.9040236),
 (7.221940199999999, 79.8636089),
 (7.0008775, 79.9775535),
 (7.0384404, 79.990718),
 (7.457272299999999, 79.82538149999999),
 (7.052583899999999, 80.066065),
 (7.0859333, 80.03341809999999),
 (7.292485000000001, 79.8572356),
 (7.0727394, 80.0157633),
 (7.2042407, 79.8940806),
 (7.873053999999999, 80.77179699999999),
 (7.2480284, 79.8993665),
 (7.205520799999999, 79.8512562),
 (6.9350919, 79.8783278),
 (6.9462153, 79.9892034),
 (6.8409891, 79.90171869999999),
 (7.577715500000001, 79.7943865),
 (6.987854, 80.0157633),
 (6.997783699999999, 79.91898139999999),
 (6.8978344, 80.0814292),
 (6.886651899999999, 79.8646835),
 (6.8743192, 79.96962769999999),
 (6.875126799999999, 79.90143379999999),
 (6.929061000000001, 79.9827754),
 (7.0477897, 79.8970348),
 (6.8014572, 79.8996789),
 (7.172484899999999, 79.8853484),
 (6.951784600000001, 79.9132991),
 (6.778670099999999, 79.9472502),
 (6.9778284, 79.9271523),
 (6.8624842, 79.8854983),
 (6.928431499999999, 79.89517339999999),
 (6.908862999999999, 79.9313567),
 (6.8411652, 79.9654324),
 (7.4817695, 80.3608876),
 (6.851095099999999, 79.92120109999999),
 (6.8135488, 79.9724245),
 (6.7879304, 79.88511419999999),
 (7.205520799999999, 79.8512562),
 (6.8649081, 79.8996789),
 (6.40053, 80.2120618),
 (6.8562846, 79.8890356),
 (6.8808992, 79.9052768),
 (7.1406334, 79.9013603),
 (6.9094108, 79.8942538),
 (6.8195453, 79.8800832),

In [20]:
def get_osrm_data(origin, destination):
    """
    Get the distance between two coordinates using OSRM API.
    :param origin: (latitude, longitude)
    :param destination: (latitude, longitude)
    :return: Distance in meters
    """
    osrm_base_url = "http://router.project-osrm.org/route/v1/car"
    url = f"{osrm_base_url}/{origin[1]},{origin[0]};{destination[1]},{destination[0]}?overview=full&geometries=geojson"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        if "routes" in data and len(data["routes"]) > 0:
            path_cords = data["routes"][0]["geometry"]["coordinates"]
            distance = data["routes"][0]["distance"] / 1000
            duration = data["routes"][0]["duration"]/ 60
            return path_cords, distance, duration
        
    return None, np.inf, np.inf

In [21]:
if locations_to_add is not None:
    locations = existing_locations
    # locations.extend(locations_to_add)
    codes = existing_codes + codes_to_add
    num_codes = len(codes)
    print(len(locations))
    print(len(codes))
    # Resize matrices if new locations are added
    if distance_matrix.shape[0] < num_codes:
        old_size = distance_matrix.shape[0]
        new_distance_matrix = np.zeros((num_codes, num_codes))
        new_duration_matrix = np.zeros((num_codes, num_codes))
        
        if old_size > 0:
            new_distance_matrix[:old_size, :old_size] = distance_matrix
            new_duration_matrix[:old_size, :old_size] = duration_matrix
        
        distance_matrix = new_distance_matrix
        duration_matrix = new_duration_matrix
        

    # route_data = []
    for i in range(num_codes):
        for j in range(i + 1, num_codes):
            if distance_matrix[i][j] == 0 or np.isinf(distance_matrix[i][j]):
                origin = locations[i]
                destination = locations[j]

                path_cords, distance, duration = get_osrm_data(origin, destination)

                distance_matrix[i][j] = round(distance, 2)
                distance_matrix[j][i] = round(distance, 2)
                
                duration_matrix[i][j] = round(duration, 2)
                duration_matrix[j][i] = round(duration, 2)
                time.sleep(0.00001)
        print(f'{i} th row proceeded')

        if i % 5 == 0:
            distance_df = pd.DataFrame(distance_matrix, index=codes, columns=codes)
            distance_df.to_csv("data/osrm_distance_matrix_new.csv")
            duration_df = pd.DataFrame(duration_matrix, index=codes, columns=codes)
            duration_df.to_csv("data/osrm_duration_matrix_new.csv")
            
            # with open("data/osrm_route_data.json", "w") as json_file:
            #     json.dump(route_data, json_file, indent=4)

    # Final save for matrices and route data
    distance_df = pd.DataFrame(distance_matrix, index=codes, columns=codes)
    distance_df.to_csv("data/osrm_distance_matrix_new.csv")
    duration_df = pd.DataFrame(duration_matrix, index=codes, columns=codes)
    duration_df.to_csv("data/osrm_duration_matrix_new.csv")
    # with open("data/osrm_route_data.json", "w") as json_file:
    #     json.dump(route_data, json_file, indent=4)
    print(f"Added {len(locations_to_add)} new unique locations with codes: {codes_to_add}")
    print("Master GPS file updated.")       
else:
    print("No location to add")

758
758
0 th row proceeded
1 th row proceeded
2 th row proceeded
3 th row proceeded
4 th row proceeded
5 th row proceeded
6 th row proceeded
7 th row proceeded
8 th row proceeded
9 th row proceeded
10 th row proceeded
11 th row proceeded
12 th row proceeded
13 th row proceeded
14 th row proceeded
15 th row proceeded
16 th row proceeded
17 th row proceeded
18 th row proceeded
19 th row proceeded
20 th row proceeded
21 th row proceeded
22 th row proceeded
23 th row proceeded
24 th row proceeded
25 th row proceeded
26 th row proceeded
27 th row proceeded
28 th row proceeded
29 th row proceeded
30 th row proceeded
31 th row proceeded
32 th row proceeded
33 th row proceeded
34 th row proceeded
35 th row proceeded
36 th row proceeded
37 th row proceeded
38 th row proceeded
39 th row proceeded
40 th row proceeded
41 th row proceeded
42 th row proceeded
43 th row proceeded
44 th row proceeded
45 th row proceeded
46 th row proceeded
47 th row proceeded
48 th row proceeded
49 th row proceeded
50 th row proceeded
51 th row proceeded
52 th row proceeded
53 th row proceeded
54 th row proceeded
55 th row proceeded
56 th row proceeded
57 th row proceeded
58 th row proceeded
59 th row proceeded
60 th row proceeded
61 th row proceeded
62 th row proceeded
63 th row proceeded
64 th row proceeded
65 th row proceeded
66 th row proceeded
67 th row proceeded
68 th row proceeded
69 th row proceeded
70 th row proceeded
71 th row proceeded
72 th row proceeded
73 th row proceeded
74 th row proceeded
75 th row proceeded
76 th row proceeded
77 th row proceeded
78 th row proceeded
79 th row proceeded
80 th row proceeded
81 th row proceeded
82 th row proceeded
83 th row proceeded
84 th row proceeded
85 th row proceeded
86 th row proceeded
87 th row proceeded
88 th row proceeded
89 th row proceeded
90 th row proceeded
91 th row proceeded
92 th row proceeded
93 th row proceeded
94 th row proceeded
95 th row proceeded
96 th row proceeded
97 th row proceeded
98 th row proceeded
99 th row proceeded
100 th row proceeded
101 th row proceeded
102 th row proceeded
103 th row proceeded
104 th row proceeded
105 th row proceeded
106 th row proceeded
107 th row proceeded
108 th row proceeded
109 th row proceeded
110 th row proceeded
111 th row proceeded
112 th row proceeded
113 th row proceeded
114 th row proceeded
115 th row proceeded
116 th row proceeded
117 th row proceeded
118 th row proceeded
119 th row proceeded
120 th row proceeded
121 th row proceeded
122 th row proceeded
123 th row proceeded
124 th row proceeded
125 th row proceeded
126 th row proceeded
127 th row proceeded
128 th row proceeded
129 th row proceeded
130 th row proceeded
131 th row proceeded
132 th row proceeded
133 th row proceeded
134 th row proceeded
135 th row proceeded
136 th row proceeded
137 th row proceeded
138 th row proceeded
139 th row proceeded
140 th row proceeded
141 th row proceeded
142 th row proceeded
143 th row proceeded
144 th row proceeded
145 th row proceeded
146 th row proceeded
147 th row proceeded
148 th row proceeded
149 th row proceeded
150 th row proceeded
151 th row proceeded
152 th row proceeded
153 th row proceeded
154 th row proceeded
155 th row proceeded
156 th row proceeded
157 th row proceeded
158 th row proceeded
159 th row proceeded
160 th row proceeded
161 th row proceeded
162 th row proceeded
163 th row proceeded
164 th row proceeded
165 th row proceeded
166 th row proceeded
167 th row proceeded
168 th row proceeded
169 th row proceeded
170 th row proceeded
171 th row proceeded
172 th row proceeded
173 th row proceeded
174 th row proceeded
175 th row proceeded
176 th row proceeded
177 th row proceeded
178 th row proceeded
179 th row proceeded
180 th row proceeded
181 th row proceeded
182 th row proceeded
183 th row proceeded
184 th row proceeded
185 th row proceeded
186 th row proceeded
187 th row proceeded
188 th row proceeded
189 th row proceeded
190 th row proceeded
191 th row proceeded
192 th row proceeded
193 th row proceeded
194 th row proceeded
195 th row proceeded
196 th row proceeded
197 th row proceeded
198 th row proceeded
199 th row proceeded
200 th row proceeded
201 th row proceeded
202 th row proceeded
203 th row proceeded
204 th row proceeded
205 th row proceeded
206 th row proceeded
207 th row proceeded
208 th row proceeded
209 th row proceeded
210 th row proceeded
211 th row proceeded
212 th row proceeded
213 th row proceeded
214 th row proceeded
215 th row proceeded
216 th row proceeded
217 th row proceeded
218 th row proceeded
219 th row proceeded
220 th row proceeded
221 th row proceeded
222 th row proceeded
223 th row proceeded
224 th row proceeded
225 th row proceeded
226 th row proceeded
227 th row proceeded
228 th row proceeded
229 th row proceeded
230 th row proceeded
231 th row proceeded
232 th row proceeded
233 th row proceeded
234 th row proceeded
235 th row proceeded
236 th row proceeded
237 th row proceeded
238 th row proceeded
239 th row proceeded
240 th row proceeded
241 th row proceeded
242 th row proceeded
243 th row proceeded
244 th row proceeded
245 th row proceeded
246 th row proceeded
247 th row proceeded
248 th row proceeded
249 th row proceeded
250 th row proceeded
251 th row proceeded
252 th row proceeded
253 th row proceeded
254 th row proceeded
255 th row proceeded
256 th row proceeded
257 th row proceeded
258 th row proceeded
259 th row proceeded
260 th row proceeded
261 th row proceeded
262 th row proceeded
263 th row proceeded
264 th row proceeded
265 th row proceeded
266 th row proceeded
267 th row proceeded
268 th row proceeded
269 th row proceeded
270 th row proceeded
271 th row proceeded
272 th row proceeded
273 th row proceeded
274 th row proceeded
275 th row proceeded
276 th row proceeded
277 th row proceeded
278 th row proceeded
279 th row proceeded
280 th row proceeded
281 th row proceeded
282 th row proceeded
283 th row proceeded
284 th row proceeded
285 th row proceeded
286 th row proceeded
287 th row proceeded
288 th row proceeded
289 th row proceeded
290 th row proceeded
291 th row proceeded
292 th row proceeded
293 th row proceeded
294 th row proceeded
295 th row proceeded
296 th row proceeded
297 th row proceeded
298 th row proceeded
299 th row proceeded
300 th row proceeded
301 th row proceeded
302 th row proceeded
303 th row proceeded
304 th row proceeded
305 th row proceeded
306 th row proceeded
307 th row proceeded
308 th row proceeded
309 th row proceeded
310 th row proceeded
311 th row proceeded
312 th row proceeded
313 th row proceeded
314 th row proceeded
315 th row proceeded
316 th row proceeded
317 th row proceeded
318 th row proceeded
319 th row proceeded
320 th row proceeded
321 th row proceeded
322 th row proceeded
323 th row proceeded
324 th row proceeded
325 th row proceeded
326 th row proceeded
327 th row proceeded
328 th row proceeded
329 th row proceeded
330 th row proceeded
331 th row proceeded
332 th row proceeded
333 th row proceeded
334 th row proceeded
335 th row proceeded
336 th row proceeded
337 th row proceeded
338 th row proceeded
339 th row proceeded
340 th row proceeded
341 th row proceeded
342 th row proceeded
343 th row proceeded
344 th row proceeded
345 th row proceeded
346 th row proceeded
347 th row proceeded
348 th row proceeded
349 th row proceeded
350 th row proceeded
351 th row proceeded
352 th row proceeded
353 th row proceeded
354 th row proceeded
355 th row proceeded
356 th row proceeded
357 th row proceeded
358 th row proceeded
359 th row proceeded
360 th row proceeded
361 th row proceeded
362 th row proceeded
363 th row proceeded
364 th row proceeded
365 th row proceeded
366 th row proceeded
367 th row proceeded
368 th row proceeded
369 th row proceeded
370 th row proceeded
371 th row proceeded
372 th row proceeded
373 th row proceeded
374 th row proceeded
375 th row proceeded
376 th row proceeded
377 th row proceeded
378 th row proceeded
379 th row proceeded
380 th row proceeded
381 th row proceeded
382 th row proceeded
383 th row proceeded
384 th row proceeded
385 th row proceeded
386 th row proceeded
387 th row proceeded
388 th row proceeded
389 th row proceeded
390 th row proceeded
391 th row proceeded
392 th row proceeded
393 th row proceeded
394 th row proceeded
395 th row proceeded
396 th row proceeded
397 th row proceeded
398 th row proceeded
399 th row proceeded
400 th row proceeded
401 th row proceeded
402 th row proceeded
403 th row proceeded
404 th row proceeded
405 th row proceeded
406 th row proceeded
407 th row proceeded
408 th row proceeded
409 th row proceeded
410 th row proceeded
411 th row proceeded
412 th row proceeded
413 th row proceeded
414 th row proceeded
415 th row proceeded
416 th row proceeded
417 th row proceeded
418 th row proceeded
419 th row proceeded
420 th row proceeded
421 th row proceeded
422 th row proceeded
423 th row proceeded
424 th row proceeded
425 th row proceeded
426 th row proceeded
427 th row proceeded
428 th row proceeded
429 th row proceeded
430 th row proceeded
431 th row proceeded
432 th row proceeded
433 th row proceeded
434 th row proceeded
435 th row proceeded
436 th row proceeded
437 th row proceeded
438 th row proceeded
439 th row proceeded
440 th row proceeded
441 th row proceeded
442 th row proceeded
443 th row proceeded
444 th row proceeded
445 th row proceeded
446 th row proceeded
447 th row proceeded
448 th row proceeded
449 th row proceeded
450 th row proceeded
451 th row proceeded
452 th row proceeded
453 th row proceeded
454 th row proceeded
455 th row proceeded
456 th row proceeded
457 th row proceeded
458 th row proceeded
459 th row proceeded
460 th row proceeded
461 th row proceeded
462 th row proceeded
463 th row proceeded
464 th row proceeded
465 th row proceeded
466 th row proceeded
467 th row proceeded
468 th row proceeded
469 th row proceeded
470 th row proceeded
471 th row proceeded
472 th row proceeded
473 th row proceeded
474 th row proceeded
475 th row proceeded
476 th row proceeded
477 th row proceeded
478 th row proceeded
479 th row proceeded
480 th row proceeded
481 th row proceeded
482 th row proceeded
483 th row proceeded
484 th row proceeded
485 th row proceeded
486 th row proceeded
487 th row proceeded
488 th row proceeded
489 th row proceeded
490 th row proceeded
491 th row proceeded
492 th row proceeded
493 th row proceeded
494 th row proceeded
495 th row proceeded
496 th row proceeded
497 th row proceeded
498 th row proceeded
499 th row proceeded
500 th row proceeded
501 th row proceeded
502 th row proceeded
503 th row proceeded
504 th row proceeded
505 th row proceeded
506 th row proceeded
507 th row proceeded
508 th row proceeded
509 th row proceeded
510 th row proceeded
511 th row proceeded
512 th row proceeded
513 th row proceeded
514 th row proceeded
515 th row proceeded
516 th row proceeded
517 th row proceeded
518 th row proceeded
519 th row proceeded
520 th row proceeded
521 th row proceeded
522 th row proceeded
523 th row proceeded
524 th row proceeded
525 th row proceeded
526 th row proceeded
527 th row proceeded
528 th row proceeded
529 th row proceeded
530 th row proceeded
531 th row proceeded
532 th row proceeded
533 th row proceeded
534 th row proceeded
535 th row proceeded
536 th row proceeded
537 th row proceeded
538 th row proceeded
539 th row proceeded
540 th row proceeded
541 th row proceeded
542 th row proceeded
543 th row proceeded
544 th row proceeded
545 th row proceeded
546 th row proceeded
547 th row proceeded
548 th row proceeded
549 th row proceeded
550 th row proceeded
551 th row proceeded
552 th row proceeded
553 th row proceeded
554 th row proceeded
555 th row proceeded
556 th row proceeded
557 th row proceeded
558 th row proceeded
559 th row proceeded
560 th row proceeded
561 th row proceeded
562 th row proceeded
563 th row proceeded
564 th row proceeded
565 th row proceeded
566 th row proceeded
567 th row proceeded
568 th row proceeded
569 th row proceeded
570 th row proceeded
571 th row proceeded
572 th row proceeded
573 th row proceeded
574 th row proceeded
575 th row proceeded
576 th row proceeded
577 th row proceeded
578 th row proceeded
579 th row proceeded
580 th row proceeded
581 th row proceeded
582 th row proceeded
583 th row proceeded
584 th row proceeded
585 th row proceeded
586 th row proceeded
587 th row proceeded
588 th row proceeded
589 th row proceeded
590 th row proceeded
591 th row proceeded
592 th row proceeded
593 th row proceeded
594 th row proceeded
595 th row proceeded
596 th row proceeded
597 th row proceeded
598 th row proceeded
599 th row proceeded
600 th row proceeded
601 th row proceeded
602 th row proceeded
603 th row proceeded
604 th row proceeded
605 th row proceeded
606 th row proceeded
607 th row proceeded
608 th row proceeded
609 th row proceeded
610 th row proceeded
611 th row proceeded
612 th row proceeded
613 th row proceeded
614 th row proceeded
615 th row proceeded
616 th row proceeded
617 th row proceeded
618 th row proceeded
619 th row proceeded
620 th row proceeded
621 th row proceeded
622 th row proceeded
623 th row proceeded
624 th row proceeded
625 th row proceeded
626 th row proceeded
627 th row proceeded
628 th row proceeded
629 th row proceeded
630 th row proceeded
631 th row proceeded
632 th row proceeded
633 th row proceeded
634 th row proceeded
635 th row proceeded
636 th row proceeded
637 th row proceeded
638 th row proceeded
639 th row proceeded
640 th row proceeded
641 th row proceeded
642 th row proceeded
643 th row proceeded
644 th row proceeded
645 th row proceeded
646 th row proceeded
647 th row proceeded
648 th row proceeded
649 th row proceeded
650 th row proceeded
651 th row proceeded
652 th row proceeded
653 th row proceeded
654 th row proceeded
655 th row proceeded
656 th row proceeded
657 th row proceeded
658 th row proceeded
659 th row proceeded
660 th row proceeded
661 th row proceeded
662 th row proceeded
663 th row proceeded
664 th row proceeded
665 th row proceeded
666 th row proceeded
667 th row proceeded
668 th row proceeded
669 th row proceeded
670 th row proceeded
671 th row proceeded
672 th row proceeded
673 th row proceeded
674 th row proceeded
675 th row proceeded
676 th row proceeded
677 th row proceeded
678 th row proceeded
679 th row proceeded
680 th row proceeded
681 th row proceeded
682 th row proceeded
683 th row proceeded
684 th row proceeded
685 th row proceeded
686 th row proceeded
687 th row proceeded
688 th row proceeded
689 th row proceeded
690 th row proceeded
691 th row proceeded
692 th row proceeded
693 th row proceeded
694 th row proceeded
695 th row proceeded
696 th row proceeded
697 th row proceeded
698 th row proceeded
699 th row proceeded
700 th row proceeded
701 th row proceeded
702 th row proceeded
703 th row proceeded
704 th row proceeded
705 th row proceeded
706 th row proceeded
707 th row proceeded
708 th row proceeded
709 th row proceeded
710 th row proceeded
711 th row proceeded
712 th row proceeded
713 th row proceeded
714 th row proceeded
715 th row proceeded
716 th row proceeded
717 th row proceeded
718 th row proceeded
719 th row proceeded
720 th row proceeded
721 th row proceeded
722 th row proceeded
723 th row proceeded
724 th row proceeded
725 th row proceeded
726 th row proceeded
727 th row proceeded
728 th row proceeded
729 th row proceeded
730 th row proceeded
731 th row proceeded
732 th row proceeded
733 th row proceeded
734 th row proceeded
735 th row proceeded
736 th row proceeded
737 th row proceeded
738 th row proceeded
739 th row proceeded
740 th row proceeded
741 th row proceeded
742 th row proceeded
743 th row proceeded
744 th row proceeded
745 th row proceeded
746 th row proceeded
747 th row proceeded
748 th row proceeded
749 th row proceeded
750 th row proceeded
751 th row proceeded
752 th row proceeded
753 th row proceeded
754 th row proceeded
755 th row proceeded
756 th row proceeded
757 th row proceeded
Added 0 new unique locations with codes: []
Master GPS file updated.